import Head from 'next/head';
import Link from 'next/link';
import { CSSProperties } from 'react';

const styles: CSSProperties = {
  display: 'grid',
  placeContent: 'center',
  height: '90vh',
};

const Home = () => (
  <>
    <Head>
      <title>Create Next App</title>
      <meta name="description" content="Generated by create next app" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main style={styles}>
      Home
      <div>
        <Link href="/post">Post</Link>
      </div>
    </main>
  </>
);

export default Home;
